name: auto_text
description: "A Flutter package that provides an auto-resizable text widget."

version: 1.0.0+1

license: MIT

homepage: 'https://github.com/MgThiha-Coding/auto_text.git'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
